spring.application.name=demo
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS:1433;encrypt=true;trustServerCertificate=true;databaseName=QuanLyDaoTao
spring.datasource.username=sa
spring.datasource.password=123123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect